export const fakeExif = {
  Make: "CASIO",
  Model: "QV-4000",
  Orientation: "top-left [8 possible values[23]]",
  Software: "Ver1.01",
  DateTime: "2003:08:11 16:45:32",
  YCbCrPositioning: "centered",
  Compression: "JPEG compression",
  XResolution: "72.0",
  YResolution: "72.0",
  ResolutionUnit: "Inch",
  ExposureTime: "1/659 s",
  FNumber: "f/4.0",
  ExposureProgram: "Normal program",
  ExifVersion: "Exif version 2.1",
  ComponentsConfiguration: "Y Cb Cr -",
  CompressedBitsPerPixel: "4.01",
  CompObj: "--",
  AudioInfo: "",
  DataObject: "",
  DocumentInfo: "",
  Extensions: "",
  GlobalInfo: "",
  Image: "",
  ImageInfo: "",
  Operation: "",
  ScreenNail: "",
  SummaryInfo: "",
  Transform: "",
  AudioStream: "",
  Contents: "",
  CurrentUser: "",
  ICC_Profile: "",
  PreviewImage: "",
  PreviewInfo: "",
  SubimageHdr: "",
  WordDocument: "",
};
