FROM tensorflow/tensorflow:latest

RUN apt-get update
RUN apt-get --yes install curl
RUN curl -LO http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
RUN bash Miniconda-latest-Linux-x86_64.sh -p /miniconda -b
RUN rm Miniconda-latest-Linux-x86_64.sh
ENV PATH=/miniconda/bin:${PATH}
RUN conda update -y conda

RUN apt update
RUN apt --yes  install libgl1-mesa-glx

ADD environment-cpu.yml /tmp/environment-cpu.yml

RUN conda env create -f /tmp/environment-cpu.yml

RUN echo "source activate $(head -1 /tmp/environment-cpu.yml | cut -d' ' -f2)" > ~/.bashrc

ENV PATH /opt/conda/envs/$(head -1 /tmp/environment-cpu.yml | cut -d' ' -f2)/bin:$PATH

RUN mkdir project

ADD . project/

WORKDIR project/

RUN pip install -e .

RUN apt update 

RUN apt-get install -y libsm6 libxext6 libxrender-dev

# RUN /miniconda/envs/wincpu/bin/conda remove tensorflow

RUN /miniconda/envs/wincpu/bin/pip uninstall --yes tensorflow

RUN /miniconda/envs/wincpu/bin/pip  install tensorflow scenedetect Pillow moviepy requests
