FROM tensorflow/tensorflow:1.15.0-gpu-py3

RUN apt-get update
RUN apt-get --yes install curl
RUN curl -LO https://repo.anaconda.com/archive/Anaconda3-2019.07-Linux-x86_64.sh 
RUN bash Anaconda3-2019.07-Linux-x86_64.sh -p /anaconda -b
RUN rm Anaconda3-2019.07-Linux-x86_64.sh
ENV PATH=/anaconda/bin:${PATH}
RUN conda update -y conda


ADD environment-gpu.yaml /tmp/environment-gpu.yaml

RUN conda env create -f /tmp/environment-gpu.yaml

RUN echo "source activate winnow-gpu" > ~/.bashrc

ENV PATH /opt/conda/envs/winnow-gpu/bin:$PATH

RUN mkdir project

ADD . project/

WORKDIR project/

RUN pip install -e .

RUN apt update 

RUN apt-get install -y libsm6 libxext6 libxrender-dev nano

RUN source activate winnow-gpu
