# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/rpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="rpc/rpc.proto",
    package="rpc.proto",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\rrpc/rpc.proto\x12\trpc.proto"M\n\x11TextSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x16\n\x0emin_similarity\x18\x02 \x01(\x02\x12\x11\n\tmax_count\x18\x03 \x01(\x05"*\n\nFoundVideo\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x10\n\x08\x64istance\x18\x02 \x01(\x02"\x9f\x01\n\x11TextSearchResults\x12%\n\x06videos\x18\x01 \x03(\x0b\x32\x15.rpc.proto.FoundVideo\x12\x16\n\x0eoriginal_query\x18\x02 \x01(\t\x12\x0e\n\x06tokens\x18\x03 \x03(\t\x12\x14\n\x0c\x63lean_tokens\x18\x04 \x03(\t\x12\x16\n\x0ehuman_readable\x18\x05 \x01(\t\x12\r\n\x05score\x18\x06 \x01(\x02\x32^\n\x0eSemanticSearch\x12L\n\x0cquery_videos\x12\x1c.rpc.proto.TextSearchRequest\x1a\x1c.rpc.proto.TextSearchResults"\x00\x62\x06proto3',
)


_TEXTSEARCHREQUEST = _descriptor.Descriptor(
    name="TextSearchRequest",
    full_name="rpc.proto.TextSearchRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="query",
            full_name="rpc.proto.TextSearchRequest.query",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="min_similarity",
            full_name="rpc.proto.TextSearchRequest.min_similarity",
            index=1,
            number=2,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="max_count",
            full_name="rpc.proto.TextSearchRequest.max_count",
            index=2,
            number=3,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=28,
    serialized_end=105,
)


_FOUNDVIDEO = _descriptor.Descriptor(
    name="FoundVideo",
    full_name="rpc.proto.FoundVideo",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="rpc.proto.FoundVideo.id",
            index=0,
            number=1,
            type=4,
            cpp_type=4,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="distance",
            full_name="rpc.proto.FoundVideo.distance",
            index=1,
            number=2,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=107,
    serialized_end=149,
)


_TEXTSEARCHRESULTS = _descriptor.Descriptor(
    name="TextSearchResults",
    full_name="rpc.proto.TextSearchResults",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="videos",
            full_name="rpc.proto.TextSearchResults.videos",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="original_query",
            full_name="rpc.proto.TextSearchResults.original_query",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="tokens",
            full_name="rpc.proto.TextSearchResults.tokens",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="clean_tokens",
            full_name="rpc.proto.TextSearchResults.clean_tokens",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="human_readable",
            full_name="rpc.proto.TextSearchResults.human_readable",
            index=4,
            number=5,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="score",
            full_name="rpc.proto.TextSearchResults.score",
            index=5,
            number=6,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=152,
    serialized_end=311,
)

_TEXTSEARCHRESULTS.fields_by_name["videos"].message_type = _FOUNDVIDEO
DESCRIPTOR.message_types_by_name["TextSearchRequest"] = _TEXTSEARCHREQUEST
DESCRIPTOR.message_types_by_name["FoundVideo"] = _FOUNDVIDEO
DESCRIPTOR.message_types_by_name["TextSearchResults"] = _TEXTSEARCHRESULTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TextSearchRequest = _reflection.GeneratedProtocolMessageType(
    "TextSearchRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _TEXTSEARCHREQUEST,
        "__module__": "rpc.rpc_pb2"
        # @@protoc_insertion_point(class_scope:rpc.proto.TextSearchRequest)
    },
)
_sym_db.RegisterMessage(TextSearchRequest)

FoundVideo = _reflection.GeneratedProtocolMessageType(
    "FoundVideo",
    (_message.Message,),
    {
        "DESCRIPTOR": _FOUNDVIDEO,
        "__module__": "rpc.rpc_pb2"
        # @@protoc_insertion_point(class_scope:rpc.proto.FoundVideo)
    },
)
_sym_db.RegisterMessage(FoundVideo)

TextSearchResults = _reflection.GeneratedProtocolMessageType(
    "TextSearchResults",
    (_message.Message,),
    {
        "DESCRIPTOR": _TEXTSEARCHRESULTS,
        "__module__": "rpc.rpc_pb2"
        # @@protoc_insertion_point(class_scope:rpc.proto.TextSearchResults)
    },
)
_sym_db.RegisterMessage(TextSearchResults)


_SEMANTICSEARCH = _descriptor.ServiceDescriptor(
    name="SemanticSearch",
    full_name="rpc.proto.SemanticSearch",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=313,
    serialized_end=407,
    methods=[
        _descriptor.MethodDescriptor(
            name="query_videos",
            full_name="rpc.proto.SemanticSearch.query_videos",
            index=0,
            containing_service=None,
            input_type=_TEXTSEARCHREQUEST,
            output_type=_TEXTSEARCHRESULTS,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_SEMANTICSEARCH)

DESCRIPTOR.services_by_name["SemanticSearch"] = _SEMANTICSEARCH

# @@protoc_insertion_point(module_scope)
