from winnow.text_search.main_utils import (
    VideoSearch,
)

# As generated by the project's feature extraction pipeline
SIGNATURES_FOLDER = "/home/stepan/work/benetech/repos/VideoDeduplication/data/representations/video_signatures"
FRAMES_FOLDER = "/home/stepan/work/benetech/repos/VideoDeduplication/data/representations/frames"

vs = VideoSearch(SIGNATURES_FOLDER)

files, distances, query_data = vs.query("soccer players")

for file, distance in zip(files, distances):
    print(file, distance)
print(query_data)
