sources:
  root: data/augmented_dataset
  extensions:
    - mp4
    - ogv
    - webm
    - avi

repr:
  directory: data/benchmark_output/representations


processing:
  frame_sampling: 1
  save_frames: true
  match_distance: 0.75
  video_list_filename: video_dataset_list.txt
  filter_dark_videos: true
  filter_dark_videos_thr: 2
  min_video_duration_seconds: 3
  detect_scenes: true
  pretrained_model_local_path: null
  keep_fileoutput: true

database:
  use: false
  uri: postgres://postgres:admin@localhost:5432/videodeduplicationdb

templates:
  source_path: data/templates/test-group/CCSI Object Recognition External/

