FROM node:14 as web

RUN mkdir /web
ADD ["web", "/web"]
WORKDIR /web

RUN npm install
RUN npm run test
RUN npm run build



FROM python:3.8

EXPOSE 5000

RUN mkdir /server
ADD ["server", "/server"]
WORKDIR /server

RUN pip install -r requirements.txt

COPY --from=web /web/build /server/static

CMD python app.py